name: restock_n_roll_mobile
description: A Flutter mobile client for Restock 'n' Roll
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
